# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edge_tracing_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets




class Ui_edge_tracing_widget(object):
    def setupUi(self, edge_tracing_widget):

        edge_tracing_widget.setObjectName("edge_tracing_widget")
        edge_tracing_widget.resize(400, 715)
        self.gridLayout = QtWidgets.QGridLayout(edge_tracing_widget)
        self.gridLayout.setObjectName("gridLayout")

        self.select_file_b = QtWidgets.QPushButton(edge_tracing_widget)
        self.select_file_b.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(12)
        font.setKerning(False)
        self.select_file_b.setFont(font)
        self.select_file_b.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.select_file_b.setObjectName("select_file_b")
        self.gridLayout.addWidget(self.select_file_b, 0, 0, 1, 3)
        self.show_original_path_cb = QtWidgets.QCheckBox(edge_tracing_widget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light SemiCondensed")
        font.setPointSize(10)
        
        
        self.show_original_path_cb.setFont(font)
        self.show_original_path_cb.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.show_original_path_cb.setObjectName("show_original_path_cb")
        self.gridLayout.addWidget(self.show_original_path_cb, 1, 0, 1, 2)
        self.original_path_colour = QtWidgets.QPushButton(edge_tracing_widget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light SemiCondensed")
        font.setPointSize(10)

        self.original_path_colour.setFont(font)
        self.original_path_colour.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.original_path_colour.setObjectName("original_path_colour")
        self.gridLayout.addWidget(self.original_path_colour, 1, 2, 1, 1)
        self.show_traced_path_cb = QtWidgets.QCheckBox(edge_tracing_widget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light SemiCondensed")
        font.setPointSize(10)

        self.show_traced_path_cb.setFont(font)
        self.show_traced_path_cb.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.show_traced_path_cb.setObjectName("show_traced_path_cb")
        self.gridLayout.addWidget(self.show_traced_path_cb, 2, 0, 1, 2)
        self.traced_path_colour = QtWidgets.QPushButton(edge_tracing_widget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light SemiCondensed")
        font.setPointSize(10)

        self.traced_path_colour.setFont(font)
        self.traced_path_colour.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.traced_path_colour.setObjectName("traced_path_colour")
        self.gridLayout.addWidget(self.traced_path_colour, 2, 2, 1, 1)
        self.show_vectors_cb = QtWidgets.QCheckBox(edge_tracing_widget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light SemiCondensed")
        font.setPointSize(10)

        self.show_vectors_cb.setFont(font)
        self.show_vectors_cb.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.show_vectors_cb.setObjectName("show_vectors_cb")
        self.gridLayout.addWidget(self.show_vectors_cb, 3, 0, 1, 1)
        self.vectors_colour = QtWidgets.QPushButton(edge_tracing_widget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light SemiCondensed")
        font.setPointSize(10)

        self.vectors_colour.setFont(font)
        self.vectors_colour.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vectors_colour.setObjectName("vectors_colour")
        self.gridLayout.addWidget(self.vectors_colour, 3, 2, 1, 1)
        self.show_circles_cb = QtWidgets.QCheckBox(edge_tracing_widget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light SemiCondensed")
        font.setPointSize(10)

        self.show_circles_cb.setFont(font)
        self.show_circles_cb.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.show_circles_cb.setObjectName("show_circles_cb")
        self.gridLayout.addWidget(self.show_circles_cb, 4, 0, 1, 1)
        self.circles_colour = QtWidgets.QPushButton(edge_tracing_widget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light SemiCondensed")
        font.setPointSize(10)

        self.circles_colour.setFont(font)
        self.circles_colour.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.circles_colour.setObjectName("circles_colour")
        self.gridLayout.addWidget(self.circles_colour, 4, 2, 1, 1)
        self.vector_count_l = QtWidgets.QLabel(edge_tracing_widget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light SemiCondensed")
        font.setPointSize(10)

        self.vector_count_l.setFont(font)
        self.vector_count_l.setObjectName("vector_count_l")
        self.gridLayout.addWidget(self.vector_count_l, 5, 0, 1, 1)

        self.vector_count_sb = QtWidgets.QSpinBox(edge_tracing_widget)
        self.vector_count_sb.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.vector_count_sb.setObjectName("vector_count_sb")
        self.gridLayout.addWidget(self.vector_count_sb, 5, 1, 1, 2)

        self.steps_l = QtWidgets.QLabel(edge_tracing_widget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light SemiCondensed")
        font.setPointSize(10)
        self.steps_l.setFont(font)
        self.steps_l.setObjectName("steps_l")
        self.gridLayout.addWidget(self.steps_l, 6, 0, 1, 1)

        self.steps_sb = QtWidgets.QSpinBox(edge_tracing_widget)
        self.steps_sb.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.steps_sb.setObjectName("steps_sb")
        self.gridLayout.addWidget(self.steps_sb, 6, 1, 1, 2)

        self.calculate_b = QtWidgets.QPushButton(edge_tracing_widget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light SemiCondensed")
        font.setPointSize(10)
        self.calculate_b.setFont(font)
        self.calculate_b.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.calculate_b.setObjectName("calculate_b")
        self.gridLayout.addWidget(self.calculate_b, 7, 0, 1, 3)

        self.change_values_b = QtWidgets.QPushButton(edge_tracing_widget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light SemiCondensed")
        font.setPointSize(10)
        self.change_values_b.setFont(font)
        self.change_values_b.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.change_values_b.setObjectName("change_values_b")
        self.gridLayout.addWidget(self.change_values_b, 8, 0, 1, 3)

        self.t_parameter_l = QtWidgets.QLabel(edge_tracing_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_parameter_l.sizePolicy().hasHeightForWidth())
        self.t_parameter_l.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(20)
        self.t_parameter_l.setFont(font)
        self.t_parameter_l.setAlignment(QtCore.Qt.AlignCenter)
        self.t_parameter_l.setObjectName("t_parameter_l")
        self.gridLayout.addWidget(self.t_parameter_l, 9, 0, 1, 2)

        self.t_parameter_lcd = QtWidgets.QLCDNumber(edge_tracing_widget)
        self.t_parameter_lcd.setObjectName("t_parameter_lcd")
        self.gridLayout.addWidget(self.t_parameter_lcd, 9, 2, 1, 1)

        self.t_parameter_slider = QtWidgets.QSlider(edge_tracing_widget)
        self.t_parameter_slider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.t_parameter_slider.setOrientation(QtCore.Qt.Horizontal)
        self.t_parameter_slider.setObjectName("t_parameter_slider")
        self.gridLayout.addWidget(self.t_parameter_slider, 10, 0, 1, 3)

        self.show_details_b = QtWidgets.QPushButton(edge_tracing_widget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light SemiCondensed")
        font.setPointSize(10)
        self.show_details_b.setFont(font)
        self.show_details_b.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.show_details_b.setObjectName("show_details_b")
        self.gridLayout.addWidget(self.show_details_b, 11, 0, 1, 2)

        self.get_animation_b = QtWidgets.QPushButton(edge_tracing_widget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light SemiCondensed")
        font.setPointSize(10)
        self.get_animation_b.setFont(font)
        self.get_animation_b.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.get_animation_b.setObjectName("get_animation_b")
        self.gridLayout.addWidget(self.get_animation_b, 11, 2, 1, 1)

        self.retranslateUi(edge_tracing_widget)
        QtCore.QMetaObject.connectSlotsByName(edge_tracing_widget)

    def retranslateUi(self, edge_tracing_widget):
        _translate = QtCore.QCoreApplication.translate
        edge_tracing_widget.setWindowTitle(_translate("edge_tracing_widget", "Form"))
        self.select_file_b.setText(_translate("edge_tracing_widget", "SELECT FILE"))
        self.show_original_path_cb.setText(_translate("edge_tracing_widget", "SHOW ORIGINAL PATH"))
        self.original_path_colour.setText(_translate("edge_tracing_widget", "PushButton"))
        self.show_traced_path_cb.setText(_translate("edge_tracing_widget", "SHOW TRACED PATH"))
        self.traced_path_colour.setText(_translate("edge_tracing_widget", "PushButton"))
        self.show_vectors_cb.setText(_translate("edge_tracing_widget", "SHOW VECTOERS"))
        self.vectors_colour.setText(_translate("edge_tracing_widget", "PushButton"))
        self.show_circles_cb.setText(_translate("edge_tracing_widget", "SHOW CIRCLES"))
        self.circles_colour.setText(_translate("edge_tracing_widget", "PushButton"))
        self.vector_count_l.setText(_translate("edge_tracing_widget", "VECTOR COUNT"))
        self.steps_l.setText(_translate("edge_tracing_widget", "STEPS"))
        self.calculate_b.setText(_translate("edge_tracing_widget", "CALCULATE"))
        self.change_values_b.setText(_translate("edge_tracing_widget", "CHANGE VALUES"))
        self.t_parameter_l.setText(_translate("edge_tracing_widget", "T PARAMETER"))
        self.show_details_b.setText(_translate("edge_tracing_widget", "SHOW DETAILS"))
        self.get_animation_b.setText(_translate("edge_tracing_widget", "GET ANIMATION"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    edge_tracing_widget = QtWidgets.QWidget()
    ui = Ui_edge_tracing_widget()
    ui.setupUi(edge_tracing_widget)
    edge_tracing_widget.show()
    sys.exit(app.exec_())
